kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin_role_binding
  namespace: risanand
subjects:
- kind: ServiceAccount
  name: risanand-admin-service-account
  namespace: risanand
roleRef:
  kind: Role
  name: admin_role
  apiGroup: rbac.authorization.k8s.io