kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namespace_admin_role_binding
  namespace: rishi
subjects:
- kind: ServiceAccount
  name: shippable-deploy
  namespace: rishi
roleRef:
  kind: Role
  name: rishi-namespace_admin_role
  apiGroup: rbac.authorization.k8s.io