kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tebhanda_role_binding
  namespace: tebhanda
subjects:
- kind: ServiceAccount
  name: tebhanda-service-account
  namespace: tebhanda
roleRef:
  kind: Role
  name: tebhanda_admin_role
  apiGroup: rbac.authorization.k8s.io