apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: gocd-agent-test
spec:
 # ------  below resource is valid for replication controller
  replicas: 2
  strategy:
    type: Recreate
  revisionHistoryLimit: 25
  # ------- end -------
  selector:
    matchLabels:
      app: gocd-agent-test
      release: test
  template:
  # ------  below labels is valid for replication controller
    metadata:
      labels:
        app: gocd-agent-test
        release: test
        rishi: anand
        # ------- end -------
    spec:
      containers:
      - name: gocd-agent
        image: test
        imagePullPolicy: Always


        volumeMounts:
        - name: ssh-keys
          mountPath: /var/go/.ssh
        - name: gcloud-keys
          mountPath: /var/go/.gcloud
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: docker-bin
          mountPath: /usr/bin/docker


        env:
        - name: "GO_SERVER"
          value: "gocd-server"
        - name: "AGENT_KEY"
          value: "something"
        - name: "AGENT_RESOURCES"
          value: "${AGENT_RESOURCES}"
        - name: "DOCKER_GID_ON_HOST"
          value: "107"


        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 512Mi

#pod.json level resource
      volumes:
      - name: ssh-keys
        secret:
          secretName: ssh-keys
      - name: gcloud-keys
        secret:
          secretName: gcloud-keys
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: docker-bin
        hostPath:
          path: /usr/bin/docker