apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-challenge-deployment
  labels:
    completed: done
spec:
  replicas: 1
  template:
    metadata:
      labels:
        completed: done
    spec:
      containers:
        - name: kubernetes-challenge
          image: rishianand/k8s:base
          ports:
            - containerPort: 4000
          env:
          - name: NAME
            valueFrom:
              configMapKeyRef:
                name: kube-challenge
                key: MY_NAME

