apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appsplusdb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webpb
    spec:
      containers:
        - name: app1
          image: emerballen/weblogicapp:app1
          ports:
            - containerPort: 7001
          volumeMounts:
            - mountPath: /u01/oracle/host
              name: appvolume
        - name: app2
          image: emerballen/weblogicapp:app2
          ports:
            - containerPort: 7001
          volumeMounts:
            - mountPath: /u01/oracle/host
              name: appvolume
        - name: oracledb
          image: emerballen/oracledemodb
          ports:
            - containerPort: 1521
      volumes:
        - name: appvolume
          persistentVolumeClaim:
            claimName: glusterclaim