//Pod with cpu and memory
apiVersion: v1        #PlacementGroupCreateTemplate
kind: Pod
metadata:
  name: frontend
spec:
  containers:              #ContainerCreateTemplate 1
  - name: db
    image: mysql
    command: ["/bin/sh"]    # TODO discuss capture command information
    args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    resources:              # TODO create pojo for limits and requests
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: wp              #ContainerCreateTemplate 2
    image: wordpress
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"