apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
    rishi: anand
    test: name
    multi: resource
    test: now
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      rishi: anand
  template:
    metadata:
      labels:
        app: nginx
        rishi: anand
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
    rishi: anand
    multi: resource
    test: now
  name: mongo-controller
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk:
            pdName: mongo-disk
            fsType: ext4