apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-new
  labels:
    app: test
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
     requests:
       storage: 1Gi