apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "pvc-from-pv"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "task-pv-volume"
  storageClassName: ""