apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: mysql-port-allow
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: mysqlpvc
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: wordpresspvc
    ports:
    - protocol: TCP
      port: 3306