apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler
  namespace: default
spec:
  volumes:
  - name: vol
    hostPath:
      path: /usr/bin
  containers:
  - name: pv-recycler
    image: "k8s.gcr.io/busybox"
    volumeMounts:
    - name: vol
      mountPath: /scrub
