apiVersion: v1
kind: Pod
metadata:
  name: redis-django
  namespace: default
  labels:
    app: web
spec:
  containers:
    - name: key-value-store
      image: redis
      ports:
        - containerPort: 6379
    - name: frontend-1
      image: django
      ports:
        - containerPort: 8000
