apiVersion: "v1"
kind: Pod
metadata:
  name: web1
  labels:
    name: web
    app: demo
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: glusterclaimabc
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
    - name: python
      image: janakiramm/py-red
      env:
        - name: "REDIS_HOST"
          value: "localhost"
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      volumeMounts:
        - mountPath: "/usr/share/nginx"
          name: task-pv-storage