apiVersion: v1
kind: Service
metadata:
  name: demo-service-fetching
  namespace: default
  labels:
    cliqr: test
spec:
  ports:
    - port: 4000
  selector:
    tier: webservicecontainer1
    cliqr: test
  type: LoadBalancer