apiVersion: v1
kind: Service
metadata:
  name: wordpress-nodeport
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
    babu: burbakiya
  type: NodePort