apiVersion: v1
kind: Service
metadata:
  name: k8s-nodeport
  labels:
    app: cloudcenter-cloudbladelp-kubernetes-11ce74
spec:
  ports:
    - port: 4000
  selector:
    app: cloudcenter-cloudbladelp-kubernetes-11ce74
  type: NodePort