kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: tebhanda
  name: tebhanda_admin_role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]