apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: test
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /ubuntu
    server: 35.184.250.142
    readOnly: false